// src/layout/MenuTrigger.tsx
import { MenuUnfoldOutlined, MenuFoldOutlined } from '@ant-design/icons-vue'

export default ({
  collapsed = false,
  setCollapsed,
}: {
  collapsed: boolean
  setCollapsed: (collapsed: boolean) => void
}) => {
  return (
    <div onClick={() => setCollapsed(!collapsed)}>
      {collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
    </div>
  )
}

// src/layout/MenuTrigger.vue
<script lang="ts" setup>
  import { MenuUnfoldOutlined, MenuFoldOutlined } from '@ant-design/icons-vue'
  import NavItem from './NavItem.vue'

  defineProps<{
    collapsed: boolean
  }>()

  const emit = defineEmits<{
    (e: 'update:collapsed', v: boolean): void
  }>()
</script>

<template>
  <NavItem class="trigger" @click="emit('update:collapsed', !collapsed)">
    <MenuUnfoldOutlined v-if="collapsed" />
    <MenuFoldOutlined v-else />
  </NavItem>
</template>

<style lang="less" scoped></style>
